/*
 * Swagger Blog
 *
 * Simple Blog
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Comment struct {
	User string `bson:"user" json:"user,omitempty"`

	ArticleId int64 `bson:"article_id" json:"article_id,omitempty"`

	Date string `bson:"date" json:"date,omitempty"`

	Content string `bson:"content" json:"content,omitempty"`
}
