/*
 * Swagger Blog
 *
 * Simple Blog
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Article struct {
	Id int64 `bson:"id" json:"id,omitempty"`

	Title string `bson:"title" json:"title,omitempty"`

	Username string `bson:"username" json:"username,omitempty"`

	Tags []Tag `bson:"tags" json:"tags,omitempty"`

	Date string `bson:"date" json:"date,omitempty"`

	Content string `bson:"content" json:"content,omitempty"`

	Comments []Comment `bson:"comments" json:"comments,omitempty"`
}
